# CI frontend jobs (format -> lint -> type-check -> test -> build)
.app-base:
  image: docker.io/library/node:22
  variables:
    CI: "true"
  before_script:
    - corepack enable
    - corepack prepare pnpm@10 --activate
    - cd app
    - pnpm install

app-build:
  extends: [".app-base"]
  stage: build
  script:
    - pnpm run build
  artifacts:
    when: always
    paths:
      - app/dist
    expire_in: 7 days

app-docs-build:
  extends: [".app-base"]
  stage: build
  script:
    - pnpm run docs
  artifacts:
    when: always
    paths:
      - app/docs
    expire_in: 7 days

app-format:
  extends: [".app-base"]
  stage: test
  script:
    - pnpm run format

app-lint:
  extends: [".app-base"]
  stage: test
  script:
    - pnpm run lint

app-type-check:
  extends: [".app-base"]
  stage: test
  script:
    - pnpm run type

app-test:
  extends: [".app-base"]
  stage: test
  script:
    - pnpm run test:ci
  artifacts:
    when: always
    reports:
      junit: app/junit-report.xml
    paths:
      - app/coverage
    expire_in: 7 days
