# CI backend jobs (extracted from .gitlab-ci.yml)
backend:
  image: ghcr.io/astral-sh/uv:debian
  stage: backend
  variables:
    PIP_NO_CACHE_DIR: "false"
  before_script:
    - cd api
    - uv sync --dev
  script:
    - uv run --no-env-file -- ruff format .
    - uv run --no-env-file -- ruff check .
    - uv run --no-env-file -- pyright --project . --warnings || true
    - mkdir -pv report
    - uv run --no-env-file -- pytest -q --junitxml=coverage/junit.xml --cov=. --cov-report=xml:coverage/coverage.xml --cov-report=html:coverage/coverage_html
  artifacts:
    when: always
    paths:
      - api/coverage/junit.xml
      - api/coverage/coverage.xml
      - api/coverage/coverage_html
    expire_in: 7 days
    reports:
      junit: api/coverage/junit.xml
