name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./app/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./app
        run: pnpm install
      - name: Format (biome)
        working-directory: ./app
        run: pnpm run format
      - name: Lint (biome)
        working-directory: ./app
        run: pnpm run lint
      - name: Type check
        working-directory: ./app
        run: pnpm run type
      - name: Run frontend tests
        working-directory: ./app
        run: pnpm run test:ci
      - name: Upload frontend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: |
            app/coverage
      - name: Build
        working-directory: ./app
        run: pnpm run build

  backend:
    name: Backend checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        working-directory: ./api
        run: uv sync --dev
      - name: Ruff format
        working-directory: ./api
        run: uv run --no-env-file -- ruff format .
      - name: Ruff lint
        working-directory: ./api
        run: uv run --no-env-file -- ruff check .
      - name: Pyright (type check)
        working-directory: ./api
        run: uv run --no-env-file -- pyright --project . --warnings
      - name: Run backend tests (with coverage)
        working-directory: ./api
        run: |
          uv run --no-env-file -- pytest -q \
            --junitxml=coverage/junit.xml \
            --cov=. \
            --cov-report=xml:coverage/coverage.xml \
            --cov-report=html:coverage/coverage_html
      - name: Upload backend test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: |
            api/.pytest_cache
            api/coverage/junit.xml
            api/coverage/coverage.xml
            api/coverage/coverage_html
