name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend (pnpm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies (app)
        working-directory: ./app
        run: pnpm install --frozen-lockfile
      - name: Build (app)
        working-directory: ./app
        run: pnpm run build
      - name: Lint (app)
        working-directory: ./app
        run: pnpm run lint || true

  backend:
    name: Backend (Python)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (api)
        working-directory: ./api
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]
      - name: Lint (api)
        working-directory: ./api
        run: |
          . .venv/bin/activate
          ruff check . || true
      - name: Type Check (api)
        working-directory: ./api
        run: |
          . .venv/bin/activate
          pyright || true
